// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "YH03TypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "YH03TypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for YH03::ObserveTypeSupport.

YH03::ObserveTypeSupport_ptr
TAO::Objref_Traits<YH03::ObserveTypeSupport>::duplicate (
    YH03::ObserveTypeSupport_ptr p)
{
  return YH03::ObserveTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<YH03::ObserveTypeSupport>::release (
    YH03::ObserveTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

YH03::ObserveTypeSupport_ptr
TAO::Objref_Traits<YH03::ObserveTypeSupport>::nil (void)
{
  return YH03::ObserveTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<YH03::ObserveTypeSupport>::marshal (
    const YH03::ObserveTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



YH03::ObserveTypeSupport::ObserveTypeSupport (void)
{}

YH03::ObserveTypeSupport::~ObserveTypeSupport (void)
{
}

YH03::ObserveTypeSupport_ptr
YH03::ObserveTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ObserveTypeSupport::_duplicate (
      dynamic_cast<ObserveTypeSupport_ptr> (_tao_objref));
}

YH03::ObserveTypeSupport_ptr
YH03::ObserveTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ObserveTypeSupport::_duplicate (
      dynamic_cast<ObserveTypeSupport_ptr> (_tao_objref));
}

YH03::ObserveTypeSupport_ptr
YH03::ObserveTypeSupport::_nil (void)
{
  return 0;
}

YH03::ObserveTypeSupport_ptr
YH03::ObserveTypeSupport::_duplicate (ObserveTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
YH03::ObserveTypeSupport::_tao_release (ObserveTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
YH03::ObserveTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:YH03/ObserveTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* YH03::ObserveTypeSupport::_interface_repository_id (void) const
{
  return "IDL:YH03/ObserveTypeSupport:1.0";
}

::CORBA::Boolean
YH03::ObserveTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for YH03::ObserveDataWriter.

YH03::ObserveDataWriter_ptr
TAO::Objref_Traits<YH03::ObserveDataWriter>::duplicate (
    YH03::ObserveDataWriter_ptr p)
{
  return YH03::ObserveDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<YH03::ObserveDataWriter>::release (
    YH03::ObserveDataWriter_ptr p)
{
  ::CORBA::release (p);
}

YH03::ObserveDataWriter_ptr
TAO::Objref_Traits<YH03::ObserveDataWriter>::nil (void)
{
  return YH03::ObserveDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<YH03::ObserveDataWriter>::marshal (
    const YH03::ObserveDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



YH03::ObserveDataWriter::ObserveDataWriter (void)
{}

YH03::ObserveDataWriter::~ObserveDataWriter (void)
{
}

YH03::ObserveDataWriter_ptr
YH03::ObserveDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ObserveDataWriter::_duplicate (
      dynamic_cast<ObserveDataWriter_ptr> (_tao_objref));
}

YH03::ObserveDataWriter_ptr
YH03::ObserveDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ObserveDataWriter::_duplicate (
      dynamic_cast<ObserveDataWriter_ptr> (_tao_objref));
}

YH03::ObserveDataWriter_ptr
YH03::ObserveDataWriter::_nil (void)
{
  return 0;
}

YH03::ObserveDataWriter_ptr
YH03::ObserveDataWriter::_duplicate (ObserveDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
YH03::ObserveDataWriter::_tao_release (ObserveDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
YH03::ObserveDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:YH03/ObserveDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* YH03::ObserveDataWriter::_interface_repository_id (void) const
{
  return "IDL:YH03/ObserveDataWriter:1.0";
}

::CORBA::Boolean
YH03::ObserveDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for YH03::ObserveDataReader.

YH03::ObserveDataReader_ptr
TAO::Objref_Traits<YH03::ObserveDataReader>::duplicate (
    YH03::ObserveDataReader_ptr p)
{
  return YH03::ObserveDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<YH03::ObserveDataReader>::release (
    YH03::ObserveDataReader_ptr p)
{
  ::CORBA::release (p);
}

YH03::ObserveDataReader_ptr
TAO::Objref_Traits<YH03::ObserveDataReader>::nil (void)
{
  return YH03::ObserveDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<YH03::ObserveDataReader>::marshal (
    const YH03::ObserveDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



YH03::ObserveDataReader::ObserveDataReader (void)
{}

YH03::ObserveDataReader::~ObserveDataReader (void)
{
}

YH03::ObserveDataReader_ptr
YH03::ObserveDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ObserveDataReader::_duplicate (
      dynamic_cast<ObserveDataReader_ptr> (_tao_objref));
}

YH03::ObserveDataReader_ptr
YH03::ObserveDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ObserveDataReader::_duplicate (
      dynamic_cast<ObserveDataReader_ptr> (_tao_objref));
}

YH03::ObserveDataReader_ptr
YH03::ObserveDataReader::_nil (void)
{
  return 0;
}

YH03::ObserveDataReader_ptr
YH03::ObserveDataReader::_duplicate (ObserveDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
YH03::ObserveDataReader::_tao_release (ObserveDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
YH03::ObserveDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:YH03/ObserveDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* YH03::ObserveDataReader::_interface_repository_id (void) const
{
  return "IDL:YH03/ObserveDataReader:1.0";
}

::CORBA::Boolean
YH03::ObserveDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

