// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "YH03C.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "YH03C.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:49

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const YH03::Observe &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.YH03_Observe_ID) &&
    (strm << _tao_aggregate.YH03_Observe_name.in ()) &&
    (strm << _tao_aggregate.YH03_Observe_pm2) &&
    (strm << _tao_aggregate.Yh03_Observe_tem) &&
    (strm << _tao_aggregate.LocalTime.in ()) &&
    (strm << _tao_aggregate.ClockTime);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    YH03::Observe &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.YH03_Observe_ID) &&
    (strm >> _tao_aggregate.YH03_Observe_name.out ()) &&
    (strm >> _tao_aggregate.YH03_Observe_pm2) &&
    (strm >> _tao_aggregate.Yh03_Observe_tem) &&
    (strm >> _tao_aggregate.LocalTime.out ()) &&
    (strm >> _tao_aggregate.ClockTime);
}

TAO_END_VERSIONED_NAMESPACE_DECL



