// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:149

#ifndef _TAO_IDL_YH03TYPESUPPORTC_UVLCJA_H_
#define _TAO_IDL_YH03TYPESUPPORTC_UVLCJA_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "YH03C.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 4 || TAO_MICRO_VERSION != 6
#error This file should be regenerated with TAO_IDL
#endif

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:35

namespace YH03
{

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:99

  typedef ::TAO::DCPS::ZeroCopyDataSeq< YH03::Observe, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> ObserveSeq;
  

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_YH03_OBSERVETYPESUPPORT__VAR_OUT_CH_)
#define _YH03_OBSERVETYPESUPPORT__VAR_OUT_CH_

  class ObserveTypeSupport;
  typedef ObserveTypeSupport *ObserveTypeSupport_ptr;
  typedef TAO_Objref_Var_T<ObserveTypeSupport> ObserveTypeSupport_var;
  typedef TAO_Objref_Out_T<ObserveTypeSupport> ObserveTypeSupport_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class  ObserveTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef ObserveTypeSupport_ptr _ptr_type;
    typedef ObserveTypeSupport_var _var_type;
    typedef ObserveTypeSupport_out _out_type;

    // The static operations.
    static ObserveTypeSupport_ptr _duplicate (ObserveTypeSupport_ptr obj);

    static void _tao_release (ObserveTypeSupport_ptr obj);

    static ObserveTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static ObserveTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ObserveTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    ObserveTypeSupport (void);

    

    virtual ~ObserveTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ObserveTypeSupport (const ObserveTypeSupport &);

    void operator= (const ObserveTypeSupport &);
  };

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_YH03_OBSERVEDATAWRITER__VAR_OUT_CH_)
#define _YH03_OBSERVEDATAWRITER__VAR_OUT_CH_

  class ObserveDataWriter;
  typedef ObserveDataWriter *ObserveDataWriter_ptr;
  typedef TAO_Objref_Var_T<ObserveDataWriter> ObserveDataWriter_var;
  typedef TAO_Objref_Out_T<ObserveDataWriter> ObserveDataWriter_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class  ObserveDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef ObserveDataWriter_ptr _ptr_type;
    typedef ObserveDataWriter_var _var_type;
    typedef ObserveDataWriter_out _out_type;

    // The static operations.
    static ObserveDataWriter_ptr _duplicate (ObserveDataWriter_ptr obj);

    static void _tao_release (ObserveDataWriter_ptr obj);

    static ObserveDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static ObserveDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ObserveDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::YH03::Observe & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::YH03::Observe & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::YH03::Observe & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::YH03::Observe & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::YH03::Observe & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::YH03::Observe & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::YH03::Observe & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::YH03::Observe & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::YH03::Observe & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::YH03::Observe & instance_data) = 0;

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    ObserveDataWriter (void);

    

    virtual ~ObserveDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ObserveDataWriter (const ObserveDataWriter &);

    void operator= (const ObserveDataWriter &);
  };

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_YH03_OBSERVEDATAREADER__VAR_OUT_CH_)
#define _YH03_OBSERVEDATAREADER__VAR_OUT_CH_

  class ObserveDataReader;
  typedef ObserveDataReader *ObserveDataReader_ptr;
  typedef TAO_Objref_Var_T<ObserveDataReader> ObserveDataReader_var;
  typedef TAO_Objref_Out_T<ObserveDataReader> ObserveDataReader_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class  ObserveDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef ObserveDataReader_ptr _ptr_type;
    typedef ObserveDataReader_var _var_type;
    typedef ObserveDataReader_out _out_type;

    // The static operations.
    static ObserveDataReader_ptr _duplicate (ObserveDataReader_ptr obj);

    static void _tao_release (ObserveDataReader_ptr obj);

    static ObserveDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static ObserveDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static ObserveDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::YH03::ObserveSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::YH03::ObserveSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::YH03::ObserveSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::YH03::ObserveSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::YH03::Observe & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::YH03::Observe & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::YH03::ObserveSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::YH03::ObserveSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::YH03::ObserveSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::YH03::ObserveSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::YH03::ObserveSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::YH03::ObserveSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::YH03::ObserveSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::YH03::ObserveSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::YH03::ObserveSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::YH03::Observe & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::YH03::Observe & instance_data) = 0;

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    ObserveDataReader (void);

    

    virtual ~ObserveDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ObserveDataReader (const ObserveDataReader &);

    void operator= (const ObserveDataReader &);
  };

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:64

} // module YH03

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_YH03_OBSERVETYPESUPPORT__TRAITS_)
#define _YH03_OBSERVETYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::YH03::ObserveTypeSupport>
  {
    static ::YH03::ObserveTypeSupport_ptr duplicate (
        ::YH03::ObserveTypeSupport_ptr p);
    static void release (
        ::YH03::ObserveTypeSupport_ptr p);
    static ::YH03::ObserveTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::YH03::ObserveTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_YH03_OBSERVEDATAWRITER__TRAITS_)
#define _YH03_OBSERVEDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::YH03::ObserveDataWriter>
  {
    static ::YH03::ObserveDataWriter_ptr duplicate (
        ::YH03::ObserveDataWriter_ptr p);
    static void release (
        ::YH03::ObserveDataWriter_ptr p);
    static ::YH03::ObserveDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::YH03::ObserveDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_YH03_OBSERVEDATAREADER__TRAITS_)
#define _YH03_OBSERVEDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::YH03::ObserveDataReader>
  {
    static ::YH03::ObserveDataReader_ptr duplicate (
        ::YH03::ObserveDataReader_ptr p);
    static void release (
        ::YH03::ObserveDataReader_ptr p);
    static ::YH03::ObserveDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::YH03::ObserveDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1686
#if defined (__ACE_INLINE__)
#include "YH03TypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

