// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "S03_TransferFileTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "S03_TransferFileTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for S03_TransferFile::FileMessageTypeSupport.

S03_TransferFile::FileMessageTypeSupport_ptr
TAO::Objref_Traits<S03_TransferFile::FileMessageTypeSupport>::duplicate (
    S03_TransferFile::FileMessageTypeSupport_ptr p)
{
  return S03_TransferFile::FileMessageTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<S03_TransferFile::FileMessageTypeSupport>::release (
    S03_TransferFile::FileMessageTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

S03_TransferFile::FileMessageTypeSupport_ptr
TAO::Objref_Traits<S03_TransferFile::FileMessageTypeSupport>::nil (void)
{
  return S03_TransferFile::FileMessageTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<S03_TransferFile::FileMessageTypeSupport>::marshal (
    const S03_TransferFile::FileMessageTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



S03_TransferFile::FileMessageTypeSupport::FileMessageTypeSupport (void)
{}

S03_TransferFile::FileMessageTypeSupport::~FileMessageTypeSupport (void)
{
}

S03_TransferFile::FileMessageTypeSupport_ptr
S03_TransferFile::FileMessageTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return FileMessageTypeSupport::_duplicate (
      dynamic_cast<FileMessageTypeSupport_ptr> (_tao_objref));
}

S03_TransferFile::FileMessageTypeSupport_ptr
S03_TransferFile::FileMessageTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return FileMessageTypeSupport::_duplicate (
      dynamic_cast<FileMessageTypeSupport_ptr> (_tao_objref));
}

S03_TransferFile::FileMessageTypeSupport_ptr
S03_TransferFile::FileMessageTypeSupport::_nil (void)
{
  return 0;
}

S03_TransferFile::FileMessageTypeSupport_ptr
S03_TransferFile::FileMessageTypeSupport::_duplicate (FileMessageTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
S03_TransferFile::FileMessageTypeSupport::_tao_release (FileMessageTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
S03_TransferFile::FileMessageTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:S03_TransferFile/FileMessageTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* S03_TransferFile::FileMessageTypeSupport::_interface_repository_id (void) const
{
  return "IDL:S03_TransferFile/FileMessageTypeSupport:1.0";
}

::CORBA::Boolean
S03_TransferFile::FileMessageTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for S03_TransferFile::FileMessageDataWriter.

S03_TransferFile::FileMessageDataWriter_ptr
TAO::Objref_Traits<S03_TransferFile::FileMessageDataWriter>::duplicate (
    S03_TransferFile::FileMessageDataWriter_ptr p)
{
  return S03_TransferFile::FileMessageDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<S03_TransferFile::FileMessageDataWriter>::release (
    S03_TransferFile::FileMessageDataWriter_ptr p)
{
  ::CORBA::release (p);
}

S03_TransferFile::FileMessageDataWriter_ptr
TAO::Objref_Traits<S03_TransferFile::FileMessageDataWriter>::nil (void)
{
  return S03_TransferFile::FileMessageDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<S03_TransferFile::FileMessageDataWriter>::marshal (
    const S03_TransferFile::FileMessageDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



S03_TransferFile::FileMessageDataWriter::FileMessageDataWriter (void)
{}

S03_TransferFile::FileMessageDataWriter::~FileMessageDataWriter (void)
{
}

S03_TransferFile::FileMessageDataWriter_ptr
S03_TransferFile::FileMessageDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return FileMessageDataWriter::_duplicate (
      dynamic_cast<FileMessageDataWriter_ptr> (_tao_objref));
}

S03_TransferFile::FileMessageDataWriter_ptr
S03_TransferFile::FileMessageDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return FileMessageDataWriter::_duplicate (
      dynamic_cast<FileMessageDataWriter_ptr> (_tao_objref));
}

S03_TransferFile::FileMessageDataWriter_ptr
S03_TransferFile::FileMessageDataWriter::_nil (void)
{
  return 0;
}

S03_TransferFile::FileMessageDataWriter_ptr
S03_TransferFile::FileMessageDataWriter::_duplicate (FileMessageDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
S03_TransferFile::FileMessageDataWriter::_tao_release (FileMessageDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
S03_TransferFile::FileMessageDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:S03_TransferFile/FileMessageDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* S03_TransferFile::FileMessageDataWriter::_interface_repository_id (void) const
{
  return "IDL:S03_TransferFile/FileMessageDataWriter:1.0";
}

::CORBA::Boolean
S03_TransferFile::FileMessageDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for S03_TransferFile::FileMessageDataReader.

S03_TransferFile::FileMessageDataReader_ptr
TAO::Objref_Traits<S03_TransferFile::FileMessageDataReader>::duplicate (
    S03_TransferFile::FileMessageDataReader_ptr p)
{
  return S03_TransferFile::FileMessageDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<S03_TransferFile::FileMessageDataReader>::release (
    S03_TransferFile::FileMessageDataReader_ptr p)
{
  ::CORBA::release (p);
}

S03_TransferFile::FileMessageDataReader_ptr
TAO::Objref_Traits<S03_TransferFile::FileMessageDataReader>::nil (void)
{
  return S03_TransferFile::FileMessageDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<S03_TransferFile::FileMessageDataReader>::marshal (
    const S03_TransferFile::FileMessageDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



S03_TransferFile::FileMessageDataReader::FileMessageDataReader (void)
{}

S03_TransferFile::FileMessageDataReader::~FileMessageDataReader (void)
{
}

S03_TransferFile::FileMessageDataReader_ptr
S03_TransferFile::FileMessageDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return FileMessageDataReader::_duplicate (
      dynamic_cast<FileMessageDataReader_ptr> (_tao_objref));
}

S03_TransferFile::FileMessageDataReader_ptr
S03_TransferFile::FileMessageDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return FileMessageDataReader::_duplicate (
      dynamic_cast<FileMessageDataReader_ptr> (_tao_objref));
}

S03_TransferFile::FileMessageDataReader_ptr
S03_TransferFile::FileMessageDataReader::_nil (void)
{
  return 0;
}

S03_TransferFile::FileMessageDataReader_ptr
S03_TransferFile::FileMessageDataReader::_duplicate (FileMessageDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
S03_TransferFile::FileMessageDataReader::_tao_release (FileMessageDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
S03_TransferFile::FileMessageDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:S03_TransferFile/FileMessageDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* S03_TransferFile::FileMessageDataReader::_interface_repository_id (void) const
{
  return "IDL:S03_TransferFile/FileMessageDataReader:1.0";
}

::CORBA::Boolean
S03_TransferFile::FileMessageDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

