// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "S03_TransferFileC.h"
#include "tao/CDR.h"
#include "tao/ORB_Core.h"

#if !defined (__ACE_INLINE__)
#include "S03_TransferFileC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_cs.cpp:105

#if !defined (_S03_TRANSFERFILE_OCTETSEQ_CS_)
#define _S03_TRANSFERFILE_OCTETSEQ_CS_

S03_TransferFile::OctetSeq::OctetSeq (void)
{}

S03_TransferFile::OctetSeq::OctetSeq (
    ::CORBA::ULong max)
  : ::TAO::unbounded_value_sequence< ::CORBA::Octet> (max)
{}

S03_TransferFile::OctetSeq::OctetSeq (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    ::CORBA::Octet * buffer,
    ::CORBA::Boolean release)
  : ::TAO::unbounded_value_sequence< ::CORBA::Octet>
    (max, length, buffer, release)
{}

S03_TransferFile::OctetSeq::OctetSeq (
    const OctetSeq &seq)
  : ::TAO::unbounded_value_sequence< ::CORBA::Octet> (seq)
{}

S03_TransferFile::OctetSeq::~OctetSeq (void)
{}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\cdr_op_cs.cpp:93
#if !defined _TAO_CDR_OP_S03_TransferFile_OctetSeq_CPP_
#define _TAO_CDR_OP_S03_TransferFile_OctetSeq_CPP_

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const S03_TransferFile::OctetSeq &_tao_sequence)
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    S03_TransferFile::OctetSeq &_tao_sequence)
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_CDR_OP_S03_TransferFile_OctetSeq_CPP_ */

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:49

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const S03_TransferFile::FileMessage &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.FileMessageID) &&
    (strm << _tao_aggregate.FileMessageTopic.in ()) &&
    (strm << _tao_aggregate.PublishMessage.in ()) &&
    (strm << _tao_aggregate.PublisherName.in ()) &&
    (strm << _tao_aggregate.FileLength) &&
    (strm << _tao_aggregate.MTime.in ()) &&
    (strm << _tao_aggregate.ClockTime) &&
    (strm << _tao_aggregate.CatchedFile.in ()) &&
    (strm << _tao_aggregate.OFile);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    S03_TransferFile::FileMessage &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.FileMessageID) &&
    (strm >> _tao_aggregate.FileMessageTopic.out ()) &&
    (strm >> _tao_aggregate.PublishMessage.out ()) &&
    (strm >> _tao_aggregate.PublisherName.out ()) &&
    (strm >> _tao_aggregate.FileLength) &&
    (strm >> _tao_aggregate.MTime.out ()) &&
    (strm >> _tao_aggregate.ClockTime) &&
    (strm >> _tao_aggregate.CatchedFile.out ()) &&
    (strm >> _tao_aggregate.OFile);
}

TAO_END_VERSIONED_NAMESPACE_DECL



