// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:149

#ifndef _TAO_IDL_S03_TRANSFERFILEC_HBZLWE_H_
#define _TAO_IDL_S03_TRANSFERFILEC_HBZLWE_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 4 || TAO_MICRO_VERSION != 6
#error This file should be regenerated with TAO_IDL
#endif

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:35

namespace S03_TransferFile
{

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:99

#if !defined (_S03_TRANSFERFILE_OCTETSEQ_CH_)
#define _S03_TRANSFERFILE_OCTETSEQ_CH_

  class OctetSeq;
  typedef ::TAO_FixedSeq_Var_T<OctetSeq> OctetSeq_var;
  typedef ::TAO_Seq_Out_T<OctetSeq> OctetSeq_out;
  

  class  OctetSeq
    : public
        ::TAO::unbounded_value_sequence< ::CORBA::Octet>
  {
  public:
    OctetSeq (void);
    OctetSeq ( ::CORBA::ULong max);
    OctetSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Octet* buffer,
      ::CORBA::Boolean release = false);
    OctetSeq (const OctetSeq &);
    virtual ~OctetSeq (void);
    

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    
    typedef OctetSeq_var _var_type;
    typedef OctetSeq_out _out_type;

    
#if (TAO_NO_COPY_OCTET_SEQUENCES == 1)
    OctetSeq (::CORBA::ULong length, const ACE_Message_Block* mb)
      : ::TAO::unbounded_value_sequence< ::CORBA::Octet> (length, mb) {}
    
#endif /* TAO_NO_COPY_OCTET_SEQUENCE == 1 */
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:258

  struct FileMessage;

  typedef
    ::TAO_Var_Var_T<
        FileMessage
      >
    FileMessage_var;

  typedef
    ::TAO_Out_T<
        FileMessage
      >
    FileMessage_out;

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\structure_ch.cpp:48

  struct  FileMessage
  {

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    
    typedef FileMessage_var _var_type;
    typedef FileMessage_out _out_type;
    
    ::CORBA::Long FileMessageID;
    ::TAO::String_Manager FileMessageTopic;
    ::TAO::String_Manager PublishMessage;
    ::TAO::String_Manager PublisherName;
    ::CORBA::Long FileLength;
    ::TAO::String_Manager MTime;
    ::CORBA::Long ClockTime;
    ::TAO::String_Manager CatchedFile;
    S03_TransferFile::OctetSeq OFile;
  };

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:64

} // module S03_TransferFile

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:683

  template<>
  class Arg_Traits< ::S03_TransferFile::OctetSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::S03_TransferFile::OctetSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:945

  template<>
  class Arg_Traits< ::S03_TransferFile::FileMessage>
    : public
        Var_Size_Arg_Traits_T<
            ::S03_TransferFile::FileMessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\cdr_op_ch.cpp:65

#if !defined _TAO_CDR_OP_S03_TransferFile_OctetSeq_H_
#define _TAO_CDR_OP_S03_TransferFile_OctetSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const S03_TransferFile::OctetSeq &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    S03_TransferFile::OctetSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_S03_TransferFile_OctetSeq_H_ */

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_ch.cpp:43


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const S03_TransferFile::FileMessage &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, S03_TransferFile::FileMessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1686
#if defined (__ACE_INLINE__)
#include "S03_TransferFileC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

