/* -*- C++ -*- */
/* Generated by ..\..\..\bin\opendds_idl version 3.12 (ACE version 6.4.6) running on input file YH02.idl */
#ifndef OPENDDS_IDL_GENERATED_YH02TYPESUPPORTIMPL_H_Q28J4R
#define OPENDDS_IDL_GENERATED_YH02TYPESUPPORTIMPL_H_Q28J4R
#include "YH02C.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DdsDcpsC.h"
#include "YH02TypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: YH02 */



/* Begin STRUCT: M02 */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const YH02::M02& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const YH02::M02& stru);

bool operator>>(Serializer& strm, YH02::M02& stru);

size_t gen_max_marshaled_size(const YH02::M02& stru, bool align);

size_t gen_max_marshaled_size(KeyOnly<const YH02::M02> stru, bool align);

void gen_find_size(KeyOnly<const YH02::M02> stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, KeyOnly<const YH02::M02> stru);

bool operator>>(Serializer& strm, KeyOnly<YH02::M02> stru);

template <>
struct MarshalTraits<YH02::M02> {
  static bool gen_is_bounded_size() { return false; }
  static bool gen_is_bounded_key_size() { return true; }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace YH02 {
// This structure supports use of std::map with a key
// defined by one or more #pragma DCPS_DATA_KEY lines.
struct  M02_OpenDDS_KeyLessThan {
  bool operator()(const YH02::M02&, const YH02::M02&) const
  {
    // Eith no DCPS_DATA_KEYs, return false
    // to allow use of map with just one entry
    return false;
  }
};
}


namespace YH02 {
class M02TypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<YH02::M02> {
  typedef YH02::M02 MessageType;
  typedef YH02::M02Seq MessageSequenceType;
  typedef YH02::M02TypeSupport TypeSupportType;
  typedef YH02::M02TypeSupportImpl TypeSupportTypeImpl;
  typedef YH02::M02DataWriter DataWriterType;
  typedef YH02::M02DataReader DataReaderType;
  typedef YH02::M02_OpenDDS_KeyLessThan LessThanType;

  static const char* type_name () { return "YH02::M02"; }
  static bool gen_has_key () { return false; }

  static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace YH02 {
class  M02TypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<M02TypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<M02> TraitsType;
  typedef M02TypeSupport TypeSupportType;
  typedef M02TypeSupport::_var_type _var_type;
  typedef M02TypeSupport::_ptr_type _ptr_type;

  M02TypeSupportImpl() {}
  virtual ~M02TypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;
  static M02TypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<YH02::M02>();
bool gen_skip_over(Serializer& ser, YH02::M02*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: M02 */

/* End MODULE: YH02 */
#endif /* OPENDDS_IDL_GENERATED_YH02TYPESUPPORTIMPL_H_Q28J4R */
