// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "YH02TypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "YH02TypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for YH02::M02TypeSupport.

YH02::M02TypeSupport_ptr
TAO::Objref_Traits<YH02::M02TypeSupport>::duplicate (
    YH02::M02TypeSupport_ptr p)
{
  return YH02::M02TypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<YH02::M02TypeSupport>::release (
    YH02::M02TypeSupport_ptr p)
{
  ::CORBA::release (p);
}

YH02::M02TypeSupport_ptr
TAO::Objref_Traits<YH02::M02TypeSupport>::nil (void)
{
  return YH02::M02TypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<YH02::M02TypeSupport>::marshal (
    const YH02::M02TypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



YH02::M02TypeSupport::M02TypeSupport (void)
{}

YH02::M02TypeSupport::~M02TypeSupport (void)
{
}

YH02::M02TypeSupport_ptr
YH02::M02TypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return M02TypeSupport::_duplicate (
      dynamic_cast<M02TypeSupport_ptr> (_tao_objref));
}

YH02::M02TypeSupport_ptr
YH02::M02TypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return M02TypeSupport::_duplicate (
      dynamic_cast<M02TypeSupport_ptr> (_tao_objref));
}

YH02::M02TypeSupport_ptr
YH02::M02TypeSupport::_nil (void)
{
  return 0;
}

YH02::M02TypeSupport_ptr
YH02::M02TypeSupport::_duplicate (M02TypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
YH02::M02TypeSupport::_tao_release (M02TypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
YH02::M02TypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:YH02/M02TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* YH02::M02TypeSupport::_interface_repository_id (void) const
{
  return "IDL:YH02/M02TypeSupport:1.0";
}

::CORBA::Boolean
YH02::M02TypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for YH02::M02DataWriter.

YH02::M02DataWriter_ptr
TAO::Objref_Traits<YH02::M02DataWriter>::duplicate (
    YH02::M02DataWriter_ptr p)
{
  return YH02::M02DataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<YH02::M02DataWriter>::release (
    YH02::M02DataWriter_ptr p)
{
  ::CORBA::release (p);
}

YH02::M02DataWriter_ptr
TAO::Objref_Traits<YH02::M02DataWriter>::nil (void)
{
  return YH02::M02DataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<YH02::M02DataWriter>::marshal (
    const YH02::M02DataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



YH02::M02DataWriter::M02DataWriter (void)
{}

YH02::M02DataWriter::~M02DataWriter (void)
{
}

YH02::M02DataWriter_ptr
YH02::M02DataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return M02DataWriter::_duplicate (
      dynamic_cast<M02DataWriter_ptr> (_tao_objref));
}

YH02::M02DataWriter_ptr
YH02::M02DataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return M02DataWriter::_duplicate (
      dynamic_cast<M02DataWriter_ptr> (_tao_objref));
}

YH02::M02DataWriter_ptr
YH02::M02DataWriter::_nil (void)
{
  return 0;
}

YH02::M02DataWriter_ptr
YH02::M02DataWriter::_duplicate (M02DataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
YH02::M02DataWriter::_tao_release (M02DataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
YH02::M02DataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:YH02/M02DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* YH02::M02DataWriter::_interface_repository_id (void) const
{
  return "IDL:YH02/M02DataWriter:1.0";
}

::CORBA::Boolean
YH02::M02DataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for YH02::M02DataReader.

YH02::M02DataReader_ptr
TAO::Objref_Traits<YH02::M02DataReader>::duplicate (
    YH02::M02DataReader_ptr p)
{
  return YH02::M02DataReader::_duplicate (p);
}

void
TAO::Objref_Traits<YH02::M02DataReader>::release (
    YH02::M02DataReader_ptr p)
{
  ::CORBA::release (p);
}

YH02::M02DataReader_ptr
TAO::Objref_Traits<YH02::M02DataReader>::nil (void)
{
  return YH02::M02DataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<YH02::M02DataReader>::marshal (
    const YH02::M02DataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



YH02::M02DataReader::M02DataReader (void)
{}

YH02::M02DataReader::~M02DataReader (void)
{
}

YH02::M02DataReader_ptr
YH02::M02DataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return M02DataReader::_duplicate (
      dynamic_cast<M02DataReader_ptr> (_tao_objref));
}

YH02::M02DataReader_ptr
YH02::M02DataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return M02DataReader::_duplicate (
      dynamic_cast<M02DataReader_ptr> (_tao_objref));
}

YH02::M02DataReader_ptr
YH02::M02DataReader::_nil (void)
{
  return 0;
}

YH02::M02DataReader_ptr
YH02::M02DataReader::_duplicate (M02DataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
YH02::M02DataReader::_tao_release (M02DataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
YH02::M02DataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:YH02/M02DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* YH02::M02DataReader::_interface_repository_id (void) const
{
  return "IDL:YH02/M02DataReader:1.0";
}

::CORBA::Boolean
YH02::M02DataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

