// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:149

#ifndef _TAO_IDL_YH02TYPESUPPORTC_YICCNU_H_
#define _TAO_IDL_YH02TYPESUPPORTC_YICCNU_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "YH02C.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 4 || TAO_MICRO_VERSION != 6
#error This file should be regenerated with TAO_IDL
#endif

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:35

namespace YH02
{

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:99

  typedef ::TAO::DCPS::ZeroCopyDataSeq< YH02::M02, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> M02Seq;
  

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_YH02_M02TYPESUPPORT__VAR_OUT_CH_)
#define _YH02_M02TYPESUPPORT__VAR_OUT_CH_

  class M02TypeSupport;
  typedef M02TypeSupport *M02TypeSupport_ptr;
  typedef TAO_Objref_Var_T<M02TypeSupport> M02TypeSupport_var;
  typedef TAO_Objref_Out_T<M02TypeSupport> M02TypeSupport_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class  M02TypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef M02TypeSupport_ptr _ptr_type;
    typedef M02TypeSupport_var _var_type;
    typedef M02TypeSupport_out _out_type;

    // The static operations.
    static M02TypeSupport_ptr _duplicate (M02TypeSupport_ptr obj);

    static void _tao_release (M02TypeSupport_ptr obj);

    static M02TypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static M02TypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static M02TypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    M02TypeSupport (void);

    

    virtual ~M02TypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    M02TypeSupport (const M02TypeSupport &);

    void operator= (const M02TypeSupport &);
  };

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_YH02_M02DATAWRITER__VAR_OUT_CH_)
#define _YH02_M02DATAWRITER__VAR_OUT_CH_

  class M02DataWriter;
  typedef M02DataWriter *M02DataWriter_ptr;
  typedef TAO_Objref_Var_T<M02DataWriter> M02DataWriter_var;
  typedef TAO_Objref_Out_T<M02DataWriter> M02DataWriter_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class  M02DataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef M02DataWriter_ptr _ptr_type;
    typedef M02DataWriter_var _var_type;
    typedef M02DataWriter_out _out_type;

    // The static operations.
    static M02DataWriter_ptr _duplicate (M02DataWriter_ptr obj);

    static void _tao_release (M02DataWriter_ptr obj);

    static M02DataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static M02DataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static M02DataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::YH02::M02 & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::YH02::M02 & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::YH02::M02 & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::YH02::M02 & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::YH02::M02 & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::YH02::M02 & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::YH02::M02 & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::YH02::M02 & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::YH02::M02 & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::YH02::M02 & instance_data) = 0;

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    M02DataWriter (void);

    

    virtual ~M02DataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    M02DataWriter (const M02DataWriter &);

    void operator= (const M02DataWriter &);
  };

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_YH02_M02DATAREADER__VAR_OUT_CH_)
#define _YH02_M02DATAREADER__VAR_OUT_CH_

  class M02DataReader;
  typedef M02DataReader *M02DataReader_ptr;
  typedef TAO_Objref_Var_T<M02DataReader> M02DataReader_var;
  typedef TAO_Objref_Out_T<M02DataReader> M02DataReader_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class  M02DataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef M02DataReader_ptr _ptr_type;
    typedef M02DataReader_var _var_type;
    typedef M02DataReader_out _out_type;

    // The static operations.
    static M02DataReader_ptr _duplicate (M02DataReader_ptr obj);

    static void _tao_release (M02DataReader_ptr obj);

    static M02DataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static M02DataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static M02DataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::YH02::M02Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::YH02::M02Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::YH02::M02Seq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::YH02::M02Seq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::YH02::M02 & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::YH02::M02 & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::YH02::M02Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::YH02::M02Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::YH02::M02Seq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::YH02::M02Seq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::YH02::M02Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::YH02::M02Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::YH02::M02Seq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::YH02::M02Seq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::YH02::M02Seq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::YH02::M02 & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::YH02::M02 & instance_data) = 0;

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    M02DataReader (void);

    

    virtual ~M02DataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    M02DataReader (const M02DataReader &);

    void operator= (const M02DataReader &);
  };

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:64

} // module YH02

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_YH02_M02TYPESUPPORT__TRAITS_)
#define _YH02_M02TYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::YH02::M02TypeSupport>
  {
    static ::YH02::M02TypeSupport_ptr duplicate (
        ::YH02::M02TypeSupport_ptr p);
    static void release (
        ::YH02::M02TypeSupport_ptr p);
    static ::YH02::M02TypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::YH02::M02TypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_YH02_M02DATAWRITER__TRAITS_)
#define _YH02_M02DATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::YH02::M02DataWriter>
  {
    static ::YH02::M02DataWriter_ptr duplicate (
        ::YH02::M02DataWriter_ptr p);
    static void release (
        ::YH02::M02DataWriter_ptr p);
    static ::YH02::M02DataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::YH02::M02DataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_YH02_M02DATAREADER__TRAITS_)
#define _YH02_M02DATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::YH02::M02DataReader>
  {
    static ::YH02::M02DataReader_ptr duplicate (
        ::YH02::M02DataReader_ptr p);
    static void release (
        ::YH02::M02DataReader_ptr p);
    static ::YH02::M02DataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::YH02::M02DataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1686
#if defined (__ACE_INLINE__)
#include "YH02TypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

