/* -*- C++ -*- */
/* Generated by ..\..\..\bin\opendds_idl version 3.12 (ACE version 6.4.6) running on input file S01_Supermarket.idl */
#ifndef OPENDDS_IDL_GENERATED_S01_SUPERMARKETTYPESUPPORTIMPL_H_WYM2DY
#define OPENDDS_IDL_GENERATED_S01_SUPERMARKETTYPESUPPORTIMPL_H_WYM2DY
#include "S01_SupermarketC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DdsDcpsC.h"
#include "S01_SupermarketTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: S01_Supermarket */



/* Begin STRUCT: UpdateInf */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const S01_Supermarket::UpdateInf& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const S01_Supermarket::UpdateInf& stru);

bool operator>>(Serializer& strm, S01_Supermarket::UpdateInf& stru);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<S01_Supermarket::UpdateInf>();
bool gen_skip_over(Serializer& ser, S01_Supermarket::UpdateInf*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: UpdateInf */


/* Begin STRUCT: DefaultInf */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const S01_Supermarket::DefaultInf& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const S01_Supermarket::DefaultInf& stru);

bool operator>>(Serializer& strm, S01_Supermarket::DefaultInf& stru);

size_t gen_max_marshaled_size(const S01_Supermarket::DefaultInf& stru, bool align);

size_t gen_max_marshaled_size(KeyOnly<const S01_Supermarket::DefaultInf> stru, bool align);

void gen_find_size(KeyOnly<const S01_Supermarket::DefaultInf> stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, KeyOnly<const S01_Supermarket::DefaultInf> stru);

bool operator>>(Serializer& strm, KeyOnly<S01_Supermarket::DefaultInf> stru);

template <>
struct MarshalTraits<S01_Supermarket::DefaultInf> {
  static bool gen_is_bounded_size() { return false; }
  static bool gen_is_bounded_key_size() { return true; }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace S01_Supermarket {
// This structure supports use of std::map with a key
// defined by one or more #pragma DCPS_DATA_KEY lines.
struct  DefaultInf_OpenDDS_KeyLessThan {
  bool operator()(const S01_Supermarket::DefaultInf&, const S01_Supermarket::DefaultInf&) const
  {
    // Eith no DCPS_DATA_KEYs, return false
    // to allow use of map with just one entry
    return false;
  }
};
}


namespace S01_Supermarket {
class DefaultInfTypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<S01_Supermarket::DefaultInf> {
  typedef S01_Supermarket::DefaultInf MessageType;
  typedef S01_Supermarket::DefaultInfSeq MessageSequenceType;
  typedef S01_Supermarket::DefaultInfTypeSupport TypeSupportType;
  typedef S01_Supermarket::DefaultInfTypeSupportImpl TypeSupportTypeImpl;
  typedef S01_Supermarket::DefaultInfDataWriter DataWriterType;
  typedef S01_Supermarket::DefaultInfDataReader DataReaderType;
  typedef S01_Supermarket::DefaultInf_OpenDDS_KeyLessThan LessThanType;

  static const char* type_name () { return "S01_Supermarket::DefaultInf"; }
  static bool gen_has_key () { return false; }

  static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace S01_Supermarket {
class  DefaultInfTypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<DefaultInfTypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<DefaultInf> TraitsType;
  typedef DefaultInfTypeSupport TypeSupportType;
  typedef DefaultInfTypeSupport::_var_type _var_type;
  typedef DefaultInfTypeSupport::_ptr_type _ptr_type;

  DefaultInfTypeSupportImpl() {}
  virtual ~DefaultInfTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;
  static DefaultInfTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<>
const MetaStruct& getMetaStruct<S01_Supermarket::DefaultInf>();
bool gen_skip_over(Serializer& ser, S01_Supermarket::DefaultInf*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: DefaultInf */

/* End MODULE: S01_Supermarket */
#endif /* OPENDDS_IDL_GENERATED_S01_SUPERMARKETTYPESUPPORTIMPL_H_WYM2DY */
