// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "S01_SupermarketC.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "S01_SupermarketC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:49

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const S01_Supermarket::UpdateInf &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.UpdateInfID) &&
    (strm << _tao_aggregate.UpdateInfTopic.in ()) &&
    (strm << _tao_aggregate.UpdateInfMessage.in ()) &&
    (strm << _tao_aggregate.PublisherName.in ()) &&
    (strm << _tao_aggregate.MTime.in ()) &&
    (strm << _tao_aggregate.ClockTime);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    S01_Supermarket::UpdateInf &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.UpdateInfID) &&
    (strm >> _tao_aggregate.UpdateInfTopic.out ()) &&
    (strm >> _tao_aggregate.UpdateInfMessage.out ()) &&
    (strm >> _tao_aggregate.PublisherName.out ()) &&
    (strm >> _tao_aggregate.MTime.out ()) &&
    (strm >> _tao_aggregate.ClockTime);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:49

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const S01_Supermarket::DefaultInf &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.DefaultInfID) &&
    (strm << _tao_aggregate.DefaultInfTopic.in ()) &&
    (strm << _tao_aggregate.DefaultInfMessage.in ()) &&
    (strm << _tao_aggregate.PublisherName.in ()) &&
    (strm << _tao_aggregate.MTime.in ()) &&
    (strm << _tao_aggregate.ClockTime);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    S01_Supermarket::DefaultInf &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.DefaultInfID) &&
    (strm >> _tao_aggregate.DefaultInfTopic.out ()) &&
    (strm >> _tao_aggregate.DefaultInfMessage.out ()) &&
    (strm >> _tao_aggregate.PublisherName.out ()) &&
    (strm >> _tao_aggregate.MTime.out ()) &&
    (strm >> _tao_aggregate.ClockTime);
}

TAO_END_VERSIONED_NAMESPACE_DECL



