// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:149

#ifndef _TAO_IDL_S01_SUPERMARKETTYPESUPPORTC_AXQQCM_H_
#define _TAO_IDL_S01_SUPERMARKETTYPESUPPORTC_AXQQCM_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "S01_SupermarketC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 4 || TAO_MICRO_VERSION != 6
#error This file should be regenerated with TAO_IDL
#endif

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:35

namespace S01_Supermarket
{

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:99

  typedef ::TAO::DCPS::ZeroCopyDataSeq< S01_Supermarket::DefaultInf, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> DefaultInfSeq;
  

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_S01_SUPERMARKET_DEFAULTINFTYPESUPPORT__VAR_OUT_CH_)
#define _S01_SUPERMARKET_DEFAULTINFTYPESUPPORT__VAR_OUT_CH_

  class DefaultInfTypeSupport;
  typedef DefaultInfTypeSupport *DefaultInfTypeSupport_ptr;
  typedef TAO_Objref_Var_T<DefaultInfTypeSupport> DefaultInfTypeSupport_var;
  typedef TAO_Objref_Out_T<DefaultInfTypeSupport> DefaultInfTypeSupport_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class  DefaultInfTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef DefaultInfTypeSupport_ptr _ptr_type;
    typedef DefaultInfTypeSupport_var _var_type;
    typedef DefaultInfTypeSupport_out _out_type;

    // The static operations.
    static DefaultInfTypeSupport_ptr _duplicate (DefaultInfTypeSupport_ptr obj);

    static void _tao_release (DefaultInfTypeSupport_ptr obj);

    static DefaultInfTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static DefaultInfTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DefaultInfTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DefaultInfTypeSupport (void);

    

    virtual ~DefaultInfTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DefaultInfTypeSupport (const DefaultInfTypeSupport &);

    void operator= (const DefaultInfTypeSupport &);
  };

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_S01_SUPERMARKET_DEFAULTINFDATAWRITER__VAR_OUT_CH_)
#define _S01_SUPERMARKET_DEFAULTINFDATAWRITER__VAR_OUT_CH_

  class DefaultInfDataWriter;
  typedef DefaultInfDataWriter *DefaultInfDataWriter_ptr;
  typedef TAO_Objref_Var_T<DefaultInfDataWriter> DefaultInfDataWriter_var;
  typedef TAO_Objref_Out_T<DefaultInfDataWriter> DefaultInfDataWriter_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class  DefaultInfDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef DefaultInfDataWriter_ptr _ptr_type;
    typedef DefaultInfDataWriter_var _var_type;
    typedef DefaultInfDataWriter_out _out_type;

    // The static operations.
    static DefaultInfDataWriter_ptr _duplicate (DefaultInfDataWriter_ptr obj);

    static void _tao_release (DefaultInfDataWriter_ptr obj);

    static DefaultInfDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static DefaultInfDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DefaultInfDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::S01_Supermarket::DefaultInf & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::S01_Supermarket::DefaultInf & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::S01_Supermarket::DefaultInf & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::S01_Supermarket::DefaultInf & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::S01_Supermarket::DefaultInf & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::S01_Supermarket::DefaultInf & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::S01_Supermarket::DefaultInf & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::S01_Supermarket::DefaultInf & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::S01_Supermarket::DefaultInf & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::S01_Supermarket::DefaultInf & instance_data) = 0;

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DefaultInfDataWriter (void);

    

    virtual ~DefaultInfDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DefaultInfDataWriter (const DefaultInfDataWriter &);

    void operator= (const DefaultInfDataWriter &);
  };

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_S01_SUPERMARKET_DEFAULTINFDATAREADER__VAR_OUT_CH_)
#define _S01_SUPERMARKET_DEFAULTINFDATAREADER__VAR_OUT_CH_

  class DefaultInfDataReader;
  typedef DefaultInfDataReader *DefaultInfDataReader_ptr;
  typedef TAO_Objref_Var_T<DefaultInfDataReader> DefaultInfDataReader_var;
  typedef TAO_Objref_Out_T<DefaultInfDataReader> DefaultInfDataReader_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class  DefaultInfDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef DefaultInfDataReader_ptr _ptr_type;
    typedef DefaultInfDataReader_var _var_type;
    typedef DefaultInfDataReader_out _out_type;

    // The static operations.
    static DefaultInfDataReader_ptr _duplicate (DefaultInfDataReader_ptr obj);

    static void _tao_release (DefaultInfDataReader_ptr obj);

    static DefaultInfDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static DefaultInfDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DefaultInfDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::S01_Supermarket::DefaultInfSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::S01_Supermarket::DefaultInfSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::S01_Supermarket::DefaultInfSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::S01_Supermarket::DefaultInfSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::S01_Supermarket::DefaultInf & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::S01_Supermarket::DefaultInf & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::S01_Supermarket::DefaultInfSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::S01_Supermarket::DefaultInfSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::S01_Supermarket::DefaultInfSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::S01_Supermarket::DefaultInfSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::S01_Supermarket::DefaultInfSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::S01_Supermarket::DefaultInfSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::S01_Supermarket::DefaultInfSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::S01_Supermarket::DefaultInfSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::S01_Supermarket::DefaultInfSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::S01_Supermarket::DefaultInf & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::S01_Supermarket::DefaultInf & instance_data) = 0;

    // TAO_IDL - Generated from
    // d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DefaultInfDataReader (void);

    

    virtual ~DefaultInfDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DefaultInfDataReader (const DefaultInfDataReader &);

    void operator= (const DefaultInfDataReader &);
  };

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:64

} // module S01_Supermarket

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_S01_SUPERMARKET_DEFAULTINFTYPESUPPORT__TRAITS_)
#define _S01_SUPERMARKET_DEFAULTINFTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::S01_Supermarket::DefaultInfTypeSupport>
  {
    static ::S01_Supermarket::DefaultInfTypeSupport_ptr duplicate (
        ::S01_Supermarket::DefaultInfTypeSupport_ptr p);
    static void release (
        ::S01_Supermarket::DefaultInfTypeSupport_ptr p);
    static ::S01_Supermarket::DefaultInfTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::S01_Supermarket::DefaultInfTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_S01_SUPERMARKET_DEFAULTINFDATAWRITER__TRAITS_)
#define _S01_SUPERMARKET_DEFAULTINFDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::S01_Supermarket::DefaultInfDataWriter>
  {
    static ::S01_Supermarket::DefaultInfDataWriter_ptr duplicate (
        ::S01_Supermarket::DefaultInfDataWriter_ptr p);
    static void release (
        ::S01_Supermarket::DefaultInfDataWriter_ptr p);
    static ::S01_Supermarket::DefaultInfDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::S01_Supermarket::DefaultInfDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_S01_SUPERMARKET_DEFAULTINFDATAREADER__TRAITS_)
#define _S01_SUPERMARKET_DEFAULTINFDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::S01_Supermarket::DefaultInfDataReader>
  {
    static ::S01_Supermarket::DefaultInfDataReader_ptr duplicate (
        ::S01_Supermarket::DefaultInfDataReader_ptr p);
    static void release (
        ::S01_Supermarket::DefaultInfDataReader_ptr p);
    static ::S01_Supermarket::DefaultInfDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::S01_Supermarket::DefaultInfDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1686
#if defined (__ACE_INLINE__)
#include "S01_SupermarketTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

