/* Generated by ..\..\..\bin\opendds_idl version 3.12 (ACE version 6.4.6) running on input file S01_Supermarket.idl */
#include "S01_SupermarketTypeSupportImpl.h"

#include <cstring>
#include <stdexcept>
#include "dds/DCPS/BuiltInTopicUtils.h"
#include "dds/DCPS/ContentFilteredTopicImpl.h"
#include "dds/DCPS/DataReaderImpl_T.h"
#include "dds/DCPS/DataWriterImpl_T.h"
#include "dds/DCPS/FilterEvaluator.h"
#include "dds/DCPS/MultiTopicDataReader_T.h"
#include "dds/DCPS/PoolAllocator.h"
#include "dds/DCPS/PublicationInstance.h"
#include "dds/DCPS/PublisherImpl.h"
#include "dds/DCPS/Qos_Helper.h"
#include "dds/DCPS/RakeData.h"
#include "dds/DCPS/RakeResults_T.h"
#include "dds/DCPS/ReceivedDataElementList.h"
#include "dds/DCPS/Registered_Data_Types.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/SubscriberImpl.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/debug.h"
#include "dds/DdsDcpsDomainC.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: S01_Supermarket */



/* Begin STRUCT: UpdateInf */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const S01_Supermarket::UpdateInf& stru, size_t& size, size_t& padding)
{
  ACE_UNUSED_ARG(stru);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(padding);
  if ((size + padding) % 4) {
    padding += 4 - ((size + padding) % 4);
  }
  size += gen_max_marshaled_size(stru.UpdateInfID);
  find_size_ulong(size, padding);
  size += ACE_OS::strlen(stru.UpdateInfTopic.in()) + 1;
  find_size_ulong(size, padding);
  size += ACE_OS::strlen(stru.UpdateInfMessage.in()) + 1;
  find_size_ulong(size, padding);
  size += ACE_OS::strlen(stru.PublisherName.in()) + 1;
  find_size_ulong(size, padding);
  size += ACE_OS::strlen(stru.MTime.in()) + 1;
  if ((size + padding) % 4) {
    padding += 4 - ((size + padding) % 4);
  }
  size += gen_max_marshaled_size(stru.ClockTime);
}

bool operator<<(Serializer& strm, const S01_Supermarket::UpdateInf& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  return (strm << stru.UpdateInfID)
    && (strm << stru.UpdateInfTopic.in())
    && (strm << stru.UpdateInfMessage.in())
    && (strm << stru.PublisherName.in())
    && (strm << stru.MTime.in())
    && (strm << stru.ClockTime);
}

bool operator>>(Serializer& strm, S01_Supermarket::UpdateInf& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  return (strm >> stru.UpdateInfID)
    && (strm >> stru.UpdateInfTopic.out())
    && (strm >> stru.UpdateInfMessage.out())
    && (strm >> stru.PublisherName.out())
    && (strm >> stru.MTime.out())
    && (strm >> stru.ClockTime);
}

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<>
struct MetaStructImpl<S01_Supermarket::UpdateInf> : MetaStruct {
  typedef S01_Supermarket::UpdateInf T;

#ifndef OPENDDS_NO_MULTI_TOPIC
  void* allocate() const { return new T; }

  void deallocate(void* stru) const { delete static_cast<T*>(stru); }
  size_t numDcpsKeys() const { return 0; }
#endif /* OPENDDS_NO_MULTI_TOPIC */

  Value getValue(const void* stru, const char* field) const
  {
    const S01_Supermarket::UpdateInf& typed = *static_cast<const S01_Supermarket::UpdateInf*>(stru);
    if (std::strcmp(field, "UpdateInfID") == 0) {
      return typed.UpdateInfID;
    }
    if (std::strcmp(field, "UpdateInfTopic") == 0) {
      return typed.UpdateInfTopic.in();
    }
    if (std::strcmp(field, "UpdateInfMessage") == 0) {
      return typed.UpdateInfMessage.in();
    }
    if (std::strcmp(field, "PublisherName") == 0) {
      return typed.PublisherName.in();
    }
    if (std::strcmp(field, "MTime") == 0) {
      return typed.MTime.in();
    }
    if (std::strcmp(field, "ClockTime") == 0) {
      return typed.ClockTime;
    }
    ACE_UNUSED_ARG(typed);
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct S01_Supermarket::UpdateInf)");
  }

  Value getValue(Serializer& ser, const char* field) const
  {
    if (std::strcmp(field, "UpdateInfID") == 0) {
      ACE_CDR::Long val;
      if (!(ser >> val)) {
        throw std::runtime_error("Field 'UpdateInfID' could not be deserialized");
      }
      return val;
    } else {
      if (!ser.skip(1, 4)) {
        throw std::runtime_error("Field 'UpdateInfID' could not be skipped");
      }
    }
    if (std::strcmp(field, "UpdateInfTopic") == 0) {
      TAO::String_Manager val;
      if (!(ser >> val.out())) {
        throw std::runtime_error("Field 'UpdateInfTopic' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(ser >> len)) {
        throw std::runtime_error("String 'UpdateInfTopic' length could not be deserialized");
      }
      if (!ser.skip(len)) {
        throw std::runtime_error("String 'UpdateInfTopic' contents could not be skipped");
      }
    }
    if (std::strcmp(field, "UpdateInfMessage") == 0) {
      TAO::String_Manager val;
      if (!(ser >> val.out())) {
        throw std::runtime_error("Field 'UpdateInfMessage' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(ser >> len)) {
        throw std::runtime_error("String 'UpdateInfMessage' length could not be deserialized");
      }
      if (!ser.skip(len)) {
        throw std::runtime_error("String 'UpdateInfMessage' contents could not be skipped");
      }
    }
    if (std::strcmp(field, "PublisherName") == 0) {
      TAO::String_Manager val;
      if (!(ser >> val.out())) {
        throw std::runtime_error("Field 'PublisherName' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(ser >> len)) {
        throw std::runtime_error("String 'PublisherName' length could not be deserialized");
      }
      if (!ser.skip(len)) {
        throw std::runtime_error("String 'PublisherName' contents could not be skipped");
      }
    }
    if (std::strcmp(field, "MTime") == 0) {
      TAO::String_Manager val;
      if (!(ser >> val.out())) {
        throw std::runtime_error("Field 'MTime' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(ser >> len)) {
        throw std::runtime_error("String 'MTime' length could not be deserialized");
      }
      if (!ser.skip(len)) {
        throw std::runtime_error("String 'MTime' contents could not be skipped");
      }
    }
    if (std::strcmp(field, "ClockTime") == 0) {
      ACE_CDR::Long val;
      if (!(ser >> val)) {
        throw std::runtime_error("Field 'ClockTime' could not be deserialized");
      }
      return val;
    } else {
      if (!ser.skip(1, 4)) {
        throw std::runtime_error("Field 'ClockTime' could not be skipped");
      }
    }
    if (!field[0]) {
      return 0;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not valid for struct S01_Supermarket::UpdateInf");
  }

  ComparatorBase::Ptr create_qc_comparator(const char* field, ComparatorBase::Ptr next) const
  {
    ACE_UNUSED_ARG(next);
    if (std::strcmp(field, "UpdateInfID") == 0) {
      return make_field_cmp(&T::UpdateInfID, next);
    }
    if (std::strcmp(field, "UpdateInfTopic") == 0) {
      return make_field_cmp(&T::UpdateInfTopic, next);
    }
    if (std::strcmp(field, "UpdateInfMessage") == 0) {
      return make_field_cmp(&T::UpdateInfMessage, next);
    }
    if (std::strcmp(field, "PublisherName") == 0) {
      return make_field_cmp(&T::PublisherName, next);
    }
    if (std::strcmp(field, "MTime") == 0) {
      return make_field_cmp(&T::MTime, next);
    }
    if (std::strcmp(field, "ClockTime") == 0) {
      return make_field_cmp(&T::ClockTime, next);
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct S01_Supermarket::UpdateInf)");
  }

#ifndef OPENDDS_NO_MULTI_TOPIC
  const char** getFieldNames() const
  {
    static const char* names[] = {"UpdateInfID", "UpdateInfTopic", "UpdateInfMessage", "PublisherName", "MTime", "ClockTime", 0};
    return names;
  }

  const void* getRawField(const void* stru, const char* field) const
  {
    if (std::strcmp(field, "UpdateInfID") == 0) {
      return &static_cast<const T*>(stru)->UpdateInfID;
    }
    if (std::strcmp(field, "UpdateInfTopic") == 0) {
      return &static_cast<const T*>(stru)->UpdateInfTopic;
    }
    if (std::strcmp(field, "UpdateInfMessage") == 0) {
      return &static_cast<const T*>(stru)->UpdateInfMessage;
    }
    if (std::strcmp(field, "PublisherName") == 0) {
      return &static_cast<const T*>(stru)->PublisherName;
    }
    if (std::strcmp(field, "MTime") == 0) {
      return &static_cast<const T*>(stru)->MTime;
    }
    if (std::strcmp(field, "ClockTime") == 0) {
      return &static_cast<const T*>(stru)->ClockTime;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct S01_Supermarket::UpdateInf)");
  }

  void assign(void* lhs, const char* field, const void* rhs,
    const char* rhsFieldSpec, const MetaStruct& rhsMeta) const
  {
    ACE_UNUSED_ARG(lhs);
    ACE_UNUSED_ARG(field);
    ACE_UNUSED_ARG(rhs);
    ACE_UNUSED_ARG(rhsFieldSpec);
    ACE_UNUSED_ARG(rhsMeta);
    if (std::strcmp(field, "UpdateInfID") == 0) {
      static_cast<T*>(lhs)->UpdateInfID = *static_cast<const CORBA::Long*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "UpdateInfTopic") == 0) {
      static_cast<T*>(lhs)->UpdateInfTopic = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "UpdateInfMessage") == 0) {
      static_cast<T*>(lhs)->UpdateInfMessage = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "PublisherName") == 0) {
      static_cast<T*>(lhs)->PublisherName = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "MTime") == 0) {
      static_cast<T*>(lhs)->MTime = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "ClockTime") == 0) {
      static_cast<T*>(lhs)->ClockTime = *static_cast<const CORBA::Long*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct S01_Supermarket::UpdateInf)");
  }
#endif /* OPENDDS_NO_MULTI_TOPIC */

  bool compare(const void* lhs, const void* rhs, const char* field) const
  {
    ACE_UNUSED_ARG(lhs);
    ACE_UNUSED_ARG(field);
    ACE_UNUSED_ARG(rhs);
    if (std::strcmp(field, "UpdateInfID") == 0) {
      return static_cast<const T*>(lhs)->UpdateInfID == static_cast<const T*>(rhs)->UpdateInfID;
    }
    if (std::strcmp(field, "UpdateInfTopic") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->UpdateInfTopic.in(), static_cast<const T*>(rhs)->UpdateInfTopic.in());
    }
    if (std::strcmp(field, "UpdateInfMessage") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->UpdateInfMessage.in(), static_cast<const T*>(rhs)->UpdateInfMessage.in());
    }
    if (std::strcmp(field, "PublisherName") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->PublisherName.in(), static_cast<const T*>(rhs)->PublisherName.in());
    }
    if (std::strcmp(field, "MTime") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->MTime.in(), static_cast<const T*>(rhs)->MTime.in());
    }
    if (std::strcmp(field, "ClockTime") == 0) {
      return static_cast<const T*>(lhs)->ClockTime == static_cast<const T*>(rhs)->ClockTime;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct S01_Supermarket::UpdateInf)");
  }
};

template<>
const MetaStruct& getMetaStruct<S01_Supermarket::UpdateInf>()
{
  static MetaStructImpl<S01_Supermarket::UpdateInf> msi;
  return msi;
}

bool gen_skip_over(Serializer& ser, S01_Supermarket::UpdateInf*)
{
  ACE_UNUSED_ARG(ser);
  MetaStructImpl<S01_Supermarket::UpdateInf>().getValue(ser, "");
  return true;
}

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: UpdateInf */


/* Begin STRUCT: DefaultInf */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const S01_Supermarket::DefaultInf& stru, size_t& size, size_t& padding)
{
  ACE_UNUSED_ARG(stru);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(padding);
  if ((size + padding) % 4) {
    padding += 4 - ((size + padding) % 4);
  }
  size += gen_max_marshaled_size(stru.DefaultInfID);
  find_size_ulong(size, padding);
  size += ACE_OS::strlen(stru.DefaultInfTopic.in()) + 1;
  find_size_ulong(size, padding);
  size += ACE_OS::strlen(stru.DefaultInfMessage.in()) + 1;
  find_size_ulong(size, padding);
  size += ACE_OS::strlen(stru.PublisherName.in()) + 1;
  find_size_ulong(size, padding);
  size += ACE_OS::strlen(stru.MTime.in()) + 1;
  if ((size + padding) % 4) {
    padding += 4 - ((size + padding) % 4);
  }
  size += gen_max_marshaled_size(stru.ClockTime);
}

bool operator<<(Serializer& strm, const S01_Supermarket::DefaultInf& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  return (strm << stru.DefaultInfID)
    && (strm << stru.DefaultInfTopic.in())
    && (strm << stru.DefaultInfMessage.in())
    && (strm << stru.PublisherName.in())
    && (strm << stru.MTime.in())
    && (strm << stru.ClockTime);
}

bool operator>>(Serializer& strm, S01_Supermarket::DefaultInf& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  return (strm >> stru.DefaultInfID)
    && (strm >> stru.DefaultInfTopic.out())
    && (strm >> stru.DefaultInfMessage.out())
    && (strm >> stru.PublisherName.out())
    && (strm >> stru.MTime.out())
    && (strm >> stru.ClockTime);
}

size_t gen_max_marshaled_size(const S01_Supermarket::DefaultInf& stru, bool align)
{
  ACE_UNUSED_ARG(stru);
  ACE_UNUSED_ARG(align);
  return 0;
}

size_t gen_max_marshaled_size(KeyOnly<const S01_Supermarket::DefaultInf> stru, bool align)
{
  ACE_UNUSED_ARG(stru);
  ACE_UNUSED_ARG(align);
  return 0;
}

void gen_find_size(KeyOnly<const S01_Supermarket::DefaultInf> stru, size_t& size, size_t& padding)
{
  ACE_UNUSED_ARG(stru);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(padding);
}

bool operator<<(Serializer& strm, KeyOnly<const S01_Supermarket::DefaultInf> stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  return true;
}

bool operator>>(Serializer& strm, KeyOnly<S01_Supermarket::DefaultInf> stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  return true;
}

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace S01_Supermarket {
::DDS::DataWriter_ptr DefaultInfTypeSupportImpl::create_datawriter()
{
  typedef OpenDDS::DCPS::DataWriterImpl_T<DefaultInf> DataWriterImplType;
  ::DDS::DataWriter_ptr writer_impl = ::DDS::DataWriter::_nil();
  ACE_NEW_NORETURN(writer_impl,
                   DataWriterImplType());
  return writer_impl;
}
::DDS::DataReader_ptr DefaultInfTypeSupportImpl::create_datareader()
{
  typedef OpenDDS::DCPS::DataReaderImpl_T<DefaultInf> DataReaderImplType;
  ::DDS::DataReader_ptr reader_impl = ::DDS::DataReader::_nil();
  ACE_NEW_NORETURN(reader_impl,
                   DataReaderImplType());
  return reader_impl;
}
#ifndef OPENDDS_NO_MULTI_TOPIC
::DDS::DataReader_ptr DefaultInfTypeSupportImpl::create_multitopic_datareader()
{
  typedef OpenDDS::DCPS::DataReaderImpl_T<DefaultInf> DataReaderImplType;
  typedef OpenDDS::DCPS::MultiTopicDataReader_T<DefaultInf, DataReaderImplType> MultiTopicDataReaderImplType;
  ::DDS::DataReader_ptr multitopic_reader_impl = ::DDS::DataReader::_nil();
  ACE_NEW_NORETURN(multitopic_reader_impl,
                   MultiTopicDataReaderImplType());
  return multitopic_reader_impl;
}
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
const OpenDDS::DCPS::MetaStruct& DefaultInfTypeSupportImpl::getMetaStructForType()
{
  return OpenDDS::DCPS::getMetaStruct<DefaultInf>();
}
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
bool DefaultInfTypeSupportImpl::has_dcps_key()
{
  return TraitsType::gen_has_key ();
}
const char* DefaultInfTypeSupportImpl::default_type_name() const
{
  return TraitsType::type_name();
}
DefaultInfTypeSupport::_ptr_type DefaultInfTypeSupportImpl::_narrow(CORBA::Object_ptr obj)
{
  return TypeSupportType::_narrow(obj);
}
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<>
struct MetaStructImpl<S01_Supermarket::DefaultInf> : MetaStruct {
  typedef S01_Supermarket::DefaultInf T;

#ifndef OPENDDS_NO_MULTI_TOPIC
  void* allocate() const { return new T; }

  void deallocate(void* stru) const { delete static_cast<T*>(stru); }
  size_t numDcpsKeys() const { return 0; }
#endif /* OPENDDS_NO_MULTI_TOPIC */

  Value getValue(const void* stru, const char* field) const
  {
    const S01_Supermarket::DefaultInf& typed = *static_cast<const S01_Supermarket::DefaultInf*>(stru);
    if (std::strcmp(field, "DefaultInfID") == 0) {
      return typed.DefaultInfID;
    }
    if (std::strcmp(field, "DefaultInfTopic") == 0) {
      return typed.DefaultInfTopic.in();
    }
    if (std::strcmp(field, "DefaultInfMessage") == 0) {
      return typed.DefaultInfMessage.in();
    }
    if (std::strcmp(field, "PublisherName") == 0) {
      return typed.PublisherName.in();
    }
    if (std::strcmp(field, "MTime") == 0) {
      return typed.MTime.in();
    }
    if (std::strcmp(field, "ClockTime") == 0) {
      return typed.ClockTime;
    }
    ACE_UNUSED_ARG(typed);
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct S01_Supermarket::DefaultInf)");
  }

  Value getValue(Serializer& ser, const char* field) const
  {
    if (std::strcmp(field, "DefaultInfID") == 0) {
      ACE_CDR::Long val;
      if (!(ser >> val)) {
        throw std::runtime_error("Field 'DefaultInfID' could not be deserialized");
      }
      return val;
    } else {
      if (!ser.skip(1, 4)) {
        throw std::runtime_error("Field 'DefaultInfID' could not be skipped");
      }
    }
    if (std::strcmp(field, "DefaultInfTopic") == 0) {
      TAO::String_Manager val;
      if (!(ser >> val.out())) {
        throw std::runtime_error("Field 'DefaultInfTopic' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(ser >> len)) {
        throw std::runtime_error("String 'DefaultInfTopic' length could not be deserialized");
      }
      if (!ser.skip(len)) {
        throw std::runtime_error("String 'DefaultInfTopic' contents could not be skipped");
      }
    }
    if (std::strcmp(field, "DefaultInfMessage") == 0) {
      TAO::String_Manager val;
      if (!(ser >> val.out())) {
        throw std::runtime_error("Field 'DefaultInfMessage' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(ser >> len)) {
        throw std::runtime_error("String 'DefaultInfMessage' length could not be deserialized");
      }
      if (!ser.skip(len)) {
        throw std::runtime_error("String 'DefaultInfMessage' contents could not be skipped");
      }
    }
    if (std::strcmp(field, "PublisherName") == 0) {
      TAO::String_Manager val;
      if (!(ser >> val.out())) {
        throw std::runtime_error("Field 'PublisherName' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(ser >> len)) {
        throw std::runtime_error("String 'PublisherName' length could not be deserialized");
      }
      if (!ser.skip(len)) {
        throw std::runtime_error("String 'PublisherName' contents could not be skipped");
      }
    }
    if (std::strcmp(field, "MTime") == 0) {
      TAO::String_Manager val;
      if (!(ser >> val.out())) {
        throw std::runtime_error("Field 'MTime' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(ser >> len)) {
        throw std::runtime_error("String 'MTime' length could not be deserialized");
      }
      if (!ser.skip(len)) {
        throw std::runtime_error("String 'MTime' contents could not be skipped");
      }
    }
    if (std::strcmp(field, "ClockTime") == 0) {
      ACE_CDR::Long val;
      if (!(ser >> val)) {
        throw std::runtime_error("Field 'ClockTime' could not be deserialized");
      }
      return val;
    } else {
      if (!ser.skip(1, 4)) {
        throw std::runtime_error("Field 'ClockTime' could not be skipped");
      }
    }
    if (!field[0]) {
      return 0;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not valid for struct S01_Supermarket::DefaultInf");
  }

  ComparatorBase::Ptr create_qc_comparator(const char* field, ComparatorBase::Ptr next) const
  {
    ACE_UNUSED_ARG(next);
    if (std::strcmp(field, "DefaultInfID") == 0) {
      return make_field_cmp(&T::DefaultInfID, next);
    }
    if (std::strcmp(field, "DefaultInfTopic") == 0) {
      return make_field_cmp(&T::DefaultInfTopic, next);
    }
    if (std::strcmp(field, "DefaultInfMessage") == 0) {
      return make_field_cmp(&T::DefaultInfMessage, next);
    }
    if (std::strcmp(field, "PublisherName") == 0) {
      return make_field_cmp(&T::PublisherName, next);
    }
    if (std::strcmp(field, "MTime") == 0) {
      return make_field_cmp(&T::MTime, next);
    }
    if (std::strcmp(field, "ClockTime") == 0) {
      return make_field_cmp(&T::ClockTime, next);
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct S01_Supermarket::DefaultInf)");
  }

#ifndef OPENDDS_NO_MULTI_TOPIC
  const char** getFieldNames() const
  {
    static const char* names[] = {"DefaultInfID", "DefaultInfTopic", "DefaultInfMessage", "PublisherName", "MTime", "ClockTime", 0};
    return names;
  }

  const void* getRawField(const void* stru, const char* field) const
  {
    if (std::strcmp(field, "DefaultInfID") == 0) {
      return &static_cast<const T*>(stru)->DefaultInfID;
    }
    if (std::strcmp(field, "DefaultInfTopic") == 0) {
      return &static_cast<const T*>(stru)->DefaultInfTopic;
    }
    if (std::strcmp(field, "DefaultInfMessage") == 0) {
      return &static_cast<const T*>(stru)->DefaultInfMessage;
    }
    if (std::strcmp(field, "PublisherName") == 0) {
      return &static_cast<const T*>(stru)->PublisherName;
    }
    if (std::strcmp(field, "MTime") == 0) {
      return &static_cast<const T*>(stru)->MTime;
    }
    if (std::strcmp(field, "ClockTime") == 0) {
      return &static_cast<const T*>(stru)->ClockTime;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct S01_Supermarket::DefaultInf)");
  }

  void assign(void* lhs, const char* field, const void* rhs,
    const char* rhsFieldSpec, const MetaStruct& rhsMeta) const
  {
    ACE_UNUSED_ARG(lhs);
    ACE_UNUSED_ARG(field);
    ACE_UNUSED_ARG(rhs);
    ACE_UNUSED_ARG(rhsFieldSpec);
    ACE_UNUSED_ARG(rhsMeta);
    if (std::strcmp(field, "DefaultInfID") == 0) {
      static_cast<T*>(lhs)->DefaultInfID = *static_cast<const CORBA::Long*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "DefaultInfTopic") == 0) {
      static_cast<T*>(lhs)->DefaultInfTopic = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "DefaultInfMessage") == 0) {
      static_cast<T*>(lhs)->DefaultInfMessage = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "PublisherName") == 0) {
      static_cast<T*>(lhs)->PublisherName = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "MTime") == 0) {
      static_cast<T*>(lhs)->MTime = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "ClockTime") == 0) {
      static_cast<T*>(lhs)->ClockTime = *static_cast<const CORBA::Long*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct S01_Supermarket::DefaultInf)");
  }
#endif /* OPENDDS_NO_MULTI_TOPIC */

  bool compare(const void* lhs, const void* rhs, const char* field) const
  {
    ACE_UNUSED_ARG(lhs);
    ACE_UNUSED_ARG(field);
    ACE_UNUSED_ARG(rhs);
    if (std::strcmp(field, "DefaultInfID") == 0) {
      return static_cast<const T*>(lhs)->DefaultInfID == static_cast<const T*>(rhs)->DefaultInfID;
    }
    if (std::strcmp(field, "DefaultInfTopic") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->DefaultInfTopic.in(), static_cast<const T*>(rhs)->DefaultInfTopic.in());
    }
    if (std::strcmp(field, "DefaultInfMessage") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->DefaultInfMessage.in(), static_cast<const T*>(rhs)->DefaultInfMessage.in());
    }
    if (std::strcmp(field, "PublisherName") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->PublisherName.in(), static_cast<const T*>(rhs)->PublisherName.in());
    }
    if (std::strcmp(field, "MTime") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->MTime.in(), static_cast<const T*>(rhs)->MTime.in());
    }
    if (std::strcmp(field, "ClockTime") == 0) {
      return static_cast<const T*>(lhs)->ClockTime == static_cast<const T*>(rhs)->ClockTime;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct S01_Supermarket::DefaultInf)");
  }
};

template<>
const MetaStruct& getMetaStruct<S01_Supermarket::DefaultInf>()
{
  static MetaStructImpl<S01_Supermarket::DefaultInf> msi;
  return msi;
}

bool gen_skip_over(Serializer& ser, S01_Supermarket::DefaultInf*)
{
  ACE_UNUSED_ARG(ser);
  MetaStructImpl<S01_Supermarket::DefaultInf>().getValue(ser, "");
  return true;
}

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: DefaultInf */

/* End MODULE: S01_Supermarket */
