// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "S01_SupermarketTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "S01_SupermarketTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for S01_Supermarket::DefaultInfTypeSupport.

S01_Supermarket::DefaultInfTypeSupport_ptr
TAO::Objref_Traits<S01_Supermarket::DefaultInfTypeSupport>::duplicate (
    S01_Supermarket::DefaultInfTypeSupport_ptr p)
{
  return S01_Supermarket::DefaultInfTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<S01_Supermarket::DefaultInfTypeSupport>::release (
    S01_Supermarket::DefaultInfTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

S01_Supermarket::DefaultInfTypeSupport_ptr
TAO::Objref_Traits<S01_Supermarket::DefaultInfTypeSupport>::nil (void)
{
  return S01_Supermarket::DefaultInfTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<S01_Supermarket::DefaultInfTypeSupport>::marshal (
    const S01_Supermarket::DefaultInfTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



S01_Supermarket::DefaultInfTypeSupport::DefaultInfTypeSupport (void)
{}

S01_Supermarket::DefaultInfTypeSupport::~DefaultInfTypeSupport (void)
{
}

S01_Supermarket::DefaultInfTypeSupport_ptr
S01_Supermarket::DefaultInfTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DefaultInfTypeSupport::_duplicate (
      dynamic_cast<DefaultInfTypeSupport_ptr> (_tao_objref));
}

S01_Supermarket::DefaultInfTypeSupport_ptr
S01_Supermarket::DefaultInfTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DefaultInfTypeSupport::_duplicate (
      dynamic_cast<DefaultInfTypeSupport_ptr> (_tao_objref));
}

S01_Supermarket::DefaultInfTypeSupport_ptr
S01_Supermarket::DefaultInfTypeSupport::_nil (void)
{
  return 0;
}

S01_Supermarket::DefaultInfTypeSupport_ptr
S01_Supermarket::DefaultInfTypeSupport::_duplicate (DefaultInfTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
S01_Supermarket::DefaultInfTypeSupport::_tao_release (DefaultInfTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
S01_Supermarket::DefaultInfTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:S01_Supermarket/DefaultInfTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* S01_Supermarket::DefaultInfTypeSupport::_interface_repository_id (void) const
{
  return "IDL:S01_Supermarket/DefaultInfTypeSupport:1.0";
}

::CORBA::Boolean
S01_Supermarket::DefaultInfTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for S01_Supermarket::DefaultInfDataWriter.

S01_Supermarket::DefaultInfDataWriter_ptr
TAO::Objref_Traits<S01_Supermarket::DefaultInfDataWriter>::duplicate (
    S01_Supermarket::DefaultInfDataWriter_ptr p)
{
  return S01_Supermarket::DefaultInfDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<S01_Supermarket::DefaultInfDataWriter>::release (
    S01_Supermarket::DefaultInfDataWriter_ptr p)
{
  ::CORBA::release (p);
}

S01_Supermarket::DefaultInfDataWriter_ptr
TAO::Objref_Traits<S01_Supermarket::DefaultInfDataWriter>::nil (void)
{
  return S01_Supermarket::DefaultInfDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<S01_Supermarket::DefaultInfDataWriter>::marshal (
    const S01_Supermarket::DefaultInfDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



S01_Supermarket::DefaultInfDataWriter::DefaultInfDataWriter (void)
{}

S01_Supermarket::DefaultInfDataWriter::~DefaultInfDataWriter (void)
{
}

S01_Supermarket::DefaultInfDataWriter_ptr
S01_Supermarket::DefaultInfDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DefaultInfDataWriter::_duplicate (
      dynamic_cast<DefaultInfDataWriter_ptr> (_tao_objref));
}

S01_Supermarket::DefaultInfDataWriter_ptr
S01_Supermarket::DefaultInfDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DefaultInfDataWriter::_duplicate (
      dynamic_cast<DefaultInfDataWriter_ptr> (_tao_objref));
}

S01_Supermarket::DefaultInfDataWriter_ptr
S01_Supermarket::DefaultInfDataWriter::_nil (void)
{
  return 0;
}

S01_Supermarket::DefaultInfDataWriter_ptr
S01_Supermarket::DefaultInfDataWriter::_duplicate (DefaultInfDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
S01_Supermarket::DefaultInfDataWriter::_tao_release (DefaultInfDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
S01_Supermarket::DefaultInfDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:S01_Supermarket/DefaultInfDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* S01_Supermarket::DefaultInfDataWriter::_interface_repository_id (void) const
{
  return "IDL:S01_Supermarket/DefaultInfDataWriter:1.0";
}

::CORBA::Boolean
S01_Supermarket::DefaultInfDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for S01_Supermarket::DefaultInfDataReader.

S01_Supermarket::DefaultInfDataReader_ptr
TAO::Objref_Traits<S01_Supermarket::DefaultInfDataReader>::duplicate (
    S01_Supermarket::DefaultInfDataReader_ptr p)
{
  return S01_Supermarket::DefaultInfDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<S01_Supermarket::DefaultInfDataReader>::release (
    S01_Supermarket::DefaultInfDataReader_ptr p)
{
  ::CORBA::release (p);
}

S01_Supermarket::DefaultInfDataReader_ptr
TAO::Objref_Traits<S01_Supermarket::DefaultInfDataReader>::nil (void)
{
  return S01_Supermarket::DefaultInfDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<S01_Supermarket::DefaultInfDataReader>::marshal (
    const S01_Supermarket::DefaultInfDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



S01_Supermarket::DefaultInfDataReader::DefaultInfDataReader (void)
{}

S01_Supermarket::DefaultInfDataReader::~DefaultInfDataReader (void)
{
}

S01_Supermarket::DefaultInfDataReader_ptr
S01_Supermarket::DefaultInfDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DefaultInfDataReader::_duplicate (
      dynamic_cast<DefaultInfDataReader_ptr> (_tao_objref));
}

S01_Supermarket::DefaultInfDataReader_ptr
S01_Supermarket::DefaultInfDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DefaultInfDataReader::_duplicate (
      dynamic_cast<DefaultInfDataReader_ptr> (_tao_objref));
}

S01_Supermarket::DefaultInfDataReader_ptr
S01_Supermarket::DefaultInfDataReader::_nil (void)
{
  return 0;
}

S01_Supermarket::DefaultInfDataReader_ptr
S01_Supermarket::DefaultInfDataReader::_duplicate (DefaultInfDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
S01_Supermarket::DefaultInfDataReader::_tao_release (DefaultInfDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
S01_Supermarket::DefaultInfDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:S01_Supermarket/DefaultInfDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* S01_Supermarket::DefaultInfDataReader::_interface_repository_id (void) const
{
  return "IDL:S01_Supermarket/DefaultInfDataReader:1.0";
}

::CORBA::Boolean
S01_Supermarket::DefaultInfDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

