// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "S02_ChatRoomTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "S02_ChatRoomTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for S02_ChatRoom::MessageTypeSupport.

S02_ChatRoom::MessageTypeSupport_ptr
TAO::Objref_Traits<S02_ChatRoom::MessageTypeSupport>::duplicate (
    S02_ChatRoom::MessageTypeSupport_ptr p)
{
  return S02_ChatRoom::MessageTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<S02_ChatRoom::MessageTypeSupport>::release (
    S02_ChatRoom::MessageTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

S02_ChatRoom::MessageTypeSupport_ptr
TAO::Objref_Traits<S02_ChatRoom::MessageTypeSupport>::nil (void)
{
  return S02_ChatRoom::MessageTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<S02_ChatRoom::MessageTypeSupport>::marshal (
    const S02_ChatRoom::MessageTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



S02_ChatRoom::MessageTypeSupport::MessageTypeSupport (void)
{}

S02_ChatRoom::MessageTypeSupport::~MessageTypeSupport (void)
{
}

S02_ChatRoom::MessageTypeSupport_ptr
S02_ChatRoom::MessageTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageTypeSupport::_duplicate (
      dynamic_cast<MessageTypeSupport_ptr> (_tao_objref));
}

S02_ChatRoom::MessageTypeSupport_ptr
S02_ChatRoom::MessageTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageTypeSupport::_duplicate (
      dynamic_cast<MessageTypeSupport_ptr> (_tao_objref));
}

S02_ChatRoom::MessageTypeSupport_ptr
S02_ChatRoom::MessageTypeSupport::_nil (void)
{
  return 0;
}

S02_ChatRoom::MessageTypeSupport_ptr
S02_ChatRoom::MessageTypeSupport::_duplicate (MessageTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
S02_ChatRoom::MessageTypeSupport::_tao_release (MessageTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
S02_ChatRoom::MessageTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:S02_ChatRoom/MessageTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* S02_ChatRoom::MessageTypeSupport::_interface_repository_id (void) const
{
  return "IDL:S02_ChatRoom/MessageTypeSupport:1.0";
}

::CORBA::Boolean
S02_ChatRoom::MessageTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for S02_ChatRoom::MessageDataWriter.

S02_ChatRoom::MessageDataWriter_ptr
TAO::Objref_Traits<S02_ChatRoom::MessageDataWriter>::duplicate (
    S02_ChatRoom::MessageDataWriter_ptr p)
{
  return S02_ChatRoom::MessageDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<S02_ChatRoom::MessageDataWriter>::release (
    S02_ChatRoom::MessageDataWriter_ptr p)
{
  ::CORBA::release (p);
}

S02_ChatRoom::MessageDataWriter_ptr
TAO::Objref_Traits<S02_ChatRoom::MessageDataWriter>::nil (void)
{
  return S02_ChatRoom::MessageDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<S02_ChatRoom::MessageDataWriter>::marshal (
    const S02_ChatRoom::MessageDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



S02_ChatRoom::MessageDataWriter::MessageDataWriter (void)
{}

S02_ChatRoom::MessageDataWriter::~MessageDataWriter (void)
{
}

S02_ChatRoom::MessageDataWriter_ptr
S02_ChatRoom::MessageDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataWriter::_duplicate (
      dynamic_cast<MessageDataWriter_ptr> (_tao_objref));
}

S02_ChatRoom::MessageDataWriter_ptr
S02_ChatRoom::MessageDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataWriter::_duplicate (
      dynamic_cast<MessageDataWriter_ptr> (_tao_objref));
}

S02_ChatRoom::MessageDataWriter_ptr
S02_ChatRoom::MessageDataWriter::_nil (void)
{
  return 0;
}

S02_ChatRoom::MessageDataWriter_ptr
S02_ChatRoom::MessageDataWriter::_duplicate (MessageDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
S02_ChatRoom::MessageDataWriter::_tao_release (MessageDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
S02_ChatRoom::MessageDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:S02_ChatRoom/MessageDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* S02_ChatRoom::MessageDataWriter::_interface_repository_id (void) const
{
  return "IDL:S02_ChatRoom/MessageDataWriter:1.0";
}

::CORBA::Boolean
S02_ChatRoom::MessageDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for S02_ChatRoom::MessageDataReader.

S02_ChatRoom::MessageDataReader_ptr
TAO::Objref_Traits<S02_ChatRoom::MessageDataReader>::duplicate (
    S02_ChatRoom::MessageDataReader_ptr p)
{
  return S02_ChatRoom::MessageDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<S02_ChatRoom::MessageDataReader>::release (
    S02_ChatRoom::MessageDataReader_ptr p)
{
  ::CORBA::release (p);
}

S02_ChatRoom::MessageDataReader_ptr
TAO::Objref_Traits<S02_ChatRoom::MessageDataReader>::nil (void)
{
  return S02_ChatRoom::MessageDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<S02_ChatRoom::MessageDataReader>::marshal (
    const S02_ChatRoom::MessageDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



S02_ChatRoom::MessageDataReader::MessageDataReader (void)
{}

S02_ChatRoom::MessageDataReader::~MessageDataReader (void)
{
}

S02_ChatRoom::MessageDataReader_ptr
S02_ChatRoom::MessageDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataReader::_duplicate (
      dynamic_cast<MessageDataReader_ptr> (_tao_objref));
}

S02_ChatRoom::MessageDataReader_ptr
S02_ChatRoom::MessageDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataReader::_duplicate (
      dynamic_cast<MessageDataReader_ptr> (_tao_objref));
}

S02_ChatRoom::MessageDataReader_ptr
S02_ChatRoom::MessageDataReader::_nil (void)
{
  return 0;
}

S02_ChatRoom::MessageDataReader_ptr
S02_ChatRoom::MessageDataReader::_duplicate (MessageDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
S02_ChatRoom::MessageDataReader::_tao_release (MessageDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
S02_ChatRoom::MessageDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:S02_ChatRoom/MessageDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* S02_ChatRoom::MessageDataReader::_interface_repository_id (void) const
{
  return "IDL:S02_ChatRoom/MessageDataReader:1.0";
}

::CORBA::Boolean
S02_ChatRoom::MessageDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

