// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.4.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "S02_ChatRoomC.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "S02_ChatRoomC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\drama\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:49

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const S02_ChatRoom::Message &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.MessageID) &&
    (strm << ::ACE_OutputCDR::from_char (_tao_aggregate.MessageType)) &&
    (strm << _tao_aggregate.MessageInf.in ()) &&
    (strm << _tao_aggregate.PublisherName.in ()) &&
    (strm << _tao_aggregate.SendTime.in ()) &&
    (strm << _tao_aggregate.Mtime);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    S02_ChatRoom::Message &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.MessageID) &&
    (strm >> ::ACE_InputCDR::to_char (_tao_aggregate.MessageType)) &&
    (strm >> _tao_aggregate.MessageInf.out ()) &&
    (strm >> _tao_aggregate.PublisherName.out ()) &&
    (strm >> _tao_aggregate.SendTime.out ()) &&
    (strm >> _tao_aggregate.Mtime);
}

TAO_END_VERSIONED_NAMESPACE_DECL



