/* -*- C++ -*- */
/* Generated by ..\..\..\bin\opendds_idl version 3.12 (ACE version 6.4.6) running on input file S02_ChatRoom.idl */
#ifndef OPENDDS_IDL_GENERATED_S02_CHATROOMTYPESUPPORTIMPL_H_86WDGV
#define OPENDDS_IDL_GENERATED_S02_CHATROOMTYPESUPPORTIMPL_H_86WDGV
#include "S02_ChatRoomC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DdsDcpsC.h"
#include "S02_ChatRoomTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: S02_ChatRoom */



/* Begin STRUCT: Message */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const S02_ChatRoom::Message& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const S02_ChatRoom::Message& stru);

bool operator>>(Serializer& strm, S02_ChatRoom::Message& stru);

size_t gen_max_marshaled_size(const S02_ChatRoom::Message& stru, bool align);

size_t gen_max_marshaled_size(KeyOnly<const S02_ChatRoom::Message> stru, bool align);

void gen_find_size(KeyOnly<const S02_ChatRoom::Message> stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, KeyOnly<const S02_ChatRoom::Message> stru);

bool operator>>(Serializer& strm, KeyOnly<S02_ChatRoom::Message> stru);

template <>
struct MarshalTraits<S02_ChatRoom::Message> {
  static bool gen_is_bounded_size() { return false; }
  static bool gen_is_bounded_key_size() { return true; }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace S02_ChatRoom {
// This structure supports use of std::map with a key
// defined by one or more #pragma DCPS_DATA_KEY lines.
struct  Message_OpenDDS_KeyLessThan {
  bool operator()(const S02_ChatRoom::Message&, const S02_ChatRoom::Message&) const
  {
    // Eith no DCPS_DATA_KEYs, return false
    // to allow use of map with just one entry
    return false;
  }
};
}


namespace S02_ChatRoom {
class MessageTypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<S02_ChatRoom::Message> {
  typedef S02_ChatRoom::Message MessageType;
  typedef S02_ChatRoom::MessageSeq MessageSequenceType;
  typedef S02_ChatRoom::MessageTypeSupport TypeSupportType;
  typedef S02_ChatRoom::MessageTypeSupportImpl TypeSupportTypeImpl;
  typedef S02_ChatRoom::MessageDataWriter DataWriterType;
  typedef S02_ChatRoom::MessageDataReader DataReaderType;
  typedef S02_ChatRoom::Message_OpenDDS_KeyLessThan LessThanType;

  static const char* type_name () { return "S02_ChatRoom::Message"; }
  static bool gen_has_key () { return false; }

  static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace S02_ChatRoom {
class  MessageTypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<MessageTypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<Message> TraitsType;
  typedef MessageTypeSupport TypeSupportType;
  typedef MessageTypeSupport::_var_type _var_type;
  typedef MessageTypeSupport::_ptr_type _ptr_type;

  MessageTypeSupportImpl() {}
  virtual ~MessageTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;
  static MessageTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<S02_ChatRoom::Message>();
bool gen_skip_over(Serializer& ser, S02_ChatRoom::Message*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: Message */

/* End MODULE: S02_ChatRoom */
#endif /* OPENDDS_IDL_GENERATED_S02_CHATROOMTYPESUPPORTIMPL_H_86WDGV */
